Repository ZB-ChalKak/chalKak-front, pull requests merged in 2023-08, with the labels that each got.

#6 [Feat] : msw & firebase
  .env
  .gitignore
  firebase/firebaseAuth.ts
  firebase/firebaseConfig.ts
  firebase/firebaseDB.ts
  mocks/browser.ts
  mocks/handlers.ts
  mocks/index.ts
  mocks/server.ts
  package-lock.json
  package.json
  pages/_app.tsx
  public/mockServiceWorker.js
Labels: Feat

#7 Fix/signup
  mocks/handlers.ts
  package-lock.json
  package.json
  pages/signup/KeywordModal.tsx
  pages/signup/index.tsx
Labels: Feat, Bug&Fix

#8 [Feat] : 알림 기능 추가
  pages/login/index.tsx
Labels: Feat

#12 [Feat] : Ft/post editor (blob, file 두가지 버전)
  .gitmessage
  firebase/firebaseStorage.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/postEditor/ImageUpload.tsx
  pages/postEditor/KeywordCheckbox.tsx
  pages/postEditor/KeywordRadioButton.tsx
  pages/postEditor/index.tsx
  utils/atoms.tsx
Labels: Feat, Bug&Fix

#13 Feat -> Dev merge
  .env
  .eslintrc.json
  .github/ISSUE_TEMPLATE/issue-template.md
  .gitignore
  .gitmessage
  .prettierrc
  firebase/firebaseAuth.ts
  firebase/firebaseConfig.ts
  firebase/firebaseDB.ts
  firebase/firebaseStorage.ts
  mocks/browser.ts
  mocks/handlers.ts
  mocks/index.ts
  mocks/server.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/components/Navbar.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/postEditor/ImageUpload.tsx
  pages/postEditor/KeywordCheckbox.tsx
  pages/postEditor/KeywordRadioButton.tsx
  pages/postEditor/index.tsx
  pages/signup/KeywordModal.tsx
  pages/signup/index.tsx
  postcss.config.js
  public/fonts/font.css
  public/fonts/notoSansKr.css
  public/images/keywordImages/댄디.png
  public/images/keywordImages/데이트룩.png
  public/images/keywordImages/미니멀.png
  public/images/keywordImages/비즈니스캐주얼.png
  public/images/keywordImages/빈티지.png
  public/images/keywordImages/스트릿.png
  public/images/keywordImages/스포티.png
  public/images/keywordImages/아메카지.png
  public/images/keywordImages/여행룩.png
  public/images/keywordImages/원마일웨어.png
  public/images/keywordImages/출근룩.png
  public/images/keywordImages/하객룩.png
  public/images/카카오.jpg
  public/mockServiceWorker.js
  styles/globals.css
  tailwind.config.ts
  utils/atoms.tsx
Labels: Feat

#14 [Feat] 메인 기능 추가
  mocks/handlers.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/components/Alert.tsx
  pages/components/Carousel.tsx
  pages/components/Navbar.tsx
  pages/components/Weather.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/main/index.tsx
  pages/postEditor/index.tsx
  styles/globals.css
  tsconfig.json
  utils/atoms.tsx
Labels: Feat

#15 [Feat] : 이미지 형식 제한
  constants/apiKeys.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/components/Divider.tsx
  pages/postEditor/GoogleMap.tsx
  pages/postEditor/ImageUpload.tsx
  pages/postEditor/index.tsx
  pages/signup/index.tsx
  utils/atoms.tsx
Labels: Feat

#16 [Feat] : mypage
  mocks/handlers.ts
  package-lock.json
  package.json
  pages/components/Navbar.tsx
  pages/login/index.tsx
  pages/userinfo/ArticleList.tsx
  pages/userinfo/index.tsx
  utils/atoms.tsx
  utils/type.ts
Labels: Feat

#17 [Feat] : 상세페이지 레이아웃
  pages/components/Navbar.tsx
  pages/login/index.tsx
  pages/posts/[postId].tsx
  pages/posts/img/여행룩.png
  pages/posts/img/프로필사진.jpg
Labels: Style

#23 [Feat] : mypage & signin
  pages/login/index.tsx
  pages/userinfo/ChangeImageModal.tsx
  pages/userinfo/index.tsx
  pages/userinfo/modify-userinfo.tsx
  utils/atoms.tsx
Labels: API, Feat

#24 [Feat] : 로그인, 네비게이션, 마이페이지
  pages/api/api.ts
  pages/api/hello.ts
  pages/components/Navbar.tsx
  pages/login/index.tsx
  pages/userinfo/index.tsx
Labels: API, Feat

#26 [Feat] 날씨 API 수정
  package.json
  pages/components/ScrollTopButton.tsx
  pages/components/Weather.tsx
  pages/login/index.tsx
  pages/main/BodyShapeModal.tsx
  pages/main/GoToPostEditorButton.tsx
  pages/main/index.tsx
  pages/search/index.tsx
Labels: Feat

#27 [Feat] : postDetail, postEditor수정 부분
  constants/apiUrl.ts
  hooks/customHooks.tsx
  next.config.js
  package-lock.json
  package.json
  pages/components/InfoAlert.tsx
  pages/postEditor/[id].tsx
  pages/postEditor/index.tsx
  pages/posts/CommentSection.tsx
  pages/posts/CommentsModal.tsx
  pages/posts/HeartsModal.tsx
  pages/posts/ShareModal.tsx
  pages/posts/[postId].tsx
  pages/signup/KeywordModal.tsx
  pages/signup/index.tsx
  styles/globals.css
Labels: Feat
