Repository ZB-ChalKak/chalKak-front, pull requests merged in 2023-09, with the labels that each got.

#29 [Feat] : 상세페이지, 작성페이지 전체적인 수정
  constants/apiUrl.ts
  pages/_app.tsx
  pages/api/api.ts
  pages/components/InfoAlert.tsx
  pages/components/WarningAlert.tsx
  pages/postEditor/[id].tsx
  pages/postEditor/index.tsx
  pages/posts/CommentSection.tsx
  pages/posts/CommentsModal.tsx
  pages/posts/HeartsModal.tsx
  pages/posts/ShareModal.tsx
  pages/posts/[postId].tsx
  pages/signup/index.tsx
  utils/atoms.tsx
Labels: API, Feat

#30 [Feat] : 스켈레톤ui추가 및 404페이지 추가
  package-lock.json
  package.json
  pages/404.tsx
  pages/components/InfoAlert.tsx
  pages/components/SkeletonPost.tsx
  pages/components/WarningAlert.tsx
  pages/postEditor/[id].tsx
  pages/postEditor/index.tsx
  pages/posts/CommentSection.tsx
  pages/posts/CommentsModal.tsx
  pages/posts/HeartsModal.tsx
  pages/posts/[postId].tsx
  pages/signup/KeywordModal.tsx
  pages/signup/SkeletonSignup.tsx
  pages/signup/index.tsx
Labels: Chore, Feat

#31 [Feat] : 키워드 필터링 추가
  pages/_app.tsx
  pages/api/api.ts
  pages/components/Weather.tsx
  pages/login/index.tsx
  pages/main/BodyShapeModal.tsx
  pages/main/index.tsx
  pages/search/index.tsx
  utils/atoms.tsx
Labels: Feat

#32 [Feat] : mypage
  firebase/firebaseAuth.ts
  firebase/firebaseConfig.ts
  firebase/firebaseDB.ts
  firebase/firebaseStorage.ts
  mocks/browser.ts
  mocks/handlers.ts
  mocks/index.ts
  mocks/server.ts
  pages/components/Navbar.tsx
  pages/login/index.tsx
  pages/userinfo/ChangeImageModal.tsx
  pages/userinfo/ChangeKeywordModal.tsx
  pages/userinfo/ChangePWModal.tsx
  pages/userinfo/ChangeUserinfoModal.tsx
  pages/userinfo/WithdrawalModal.tsx
  pages/userinfo/index.tsx
  pages/userinfo/modify-userinfo.tsx
  utils/atoms.tsx
  utils/type.ts
Labels: API, Feat

#38 Ft/mypage
  pages/404.tsx
  pages/api/api.ts
  pages/components/Navbar.tsx
  pages/following/index.tsx
  pages/login/index.tsx
  pages/modify-userinfo/ChangeImageModal.tsx
  pages/modify-userinfo/ChangePWModal.tsx
  pages/modify-userinfo/ChangeUserinfoModal.tsx
  pages/modify-userinfo/ModifyButton.tsx
  pages/modify-userinfo/WithdrawalModal.tsx
  pages/modify-userinfo/[userId].tsx
  pages/userinfo/FollowerModal.tsx
  pages/userinfo/FollowingModal.tsx
  pages/userinfo/[userId].tsx
  pages/userinfo/index.tsx
  utils/atoms.tsx
  utils/type.ts
Labels: API, Feat

#39 [Feat] : 메인 페이지 수정 및 기능 추가
  pages/components/ScrollTopButton.tsx
  pages/login/index.tsx
  pages/main/BodyShapeModal.tsx
  pages/main/GoToPostEditorButton.tsx
  pages/main/index.tsx
  pages/userinfo/ChangeKeywordModal.tsx
  pages/userinfo/ChangeUserinfoModal.tsx
  utils/atoms.tsx
Labels: Feat

#41 [Feat] : navbar 수정 및 반응형 웹 수정
  next.config.js
  pages/api/api.ts
  pages/components/Navbar.tsx
  pages/components/SkeletonPost.tsx
  pages/emailAuthPage/index.tsx
  pages/login/index.tsx
  pages/postEditor/GoogleMap.tsx
  pages/postEditor/index.tsx
  pages/posts/CommentSection.tsx
  pages/posts/CommentsModal.tsx
  pages/posts/HeartsModal.tsx
  pages/posts/[postId].tsx
  pages/signup/KeywordModal.tsx
  pages/signup/index.tsx
  public/images/defaultImg.jpg
  public/images/카카오.jpg
  styles/globals.css
  tailwind.config.ts
  utils/atoms.tsx
Labels: Chore, Bug&Fix, Style

#45 [Chore] : 주석 제거, 콘솔 로그 제거, 구글 로그인 구현 중
  pages/following/index.tsx
  pages/login/index.tsx
  pages/modify-userinfo/ChangeImageModal.tsx
  pages/modify-userinfo/ChangePWModal.tsx
  pages/modify-userinfo/ChangeUserinfoModal.tsx
  pages/modify-userinfo/[userId].tsx
  pages/userinfo/FollowerModal.tsx
  pages/userinfo/FollowingModal.tsx
  pages/userinfo/[userId].tsx
Labels: Chore

#46 ✨ [Feat] : 날씨 추천 기능, api 중복 해결
  package-lock.json
  package.json
  pages/components/Carousel.tsx
  pages/components/Navbar.tsx
  pages/components/Weather.tsx
  pages/main/BodyShapeModal.tsx
  pages/main/GoToPostEditorButton.tsx
  pages/main/index.tsx
  pages/search/index.tsx
  utils/atoms.tsx
Labels: Feat

#47 [Feat] : 회원 정보 수정 및 구글 로그인
  pages/login/index.tsx
  pages/modify-userinfo/ChangeUserinfoModal.tsx
  pages/modify-userinfo/[userId].tsx
Labels: API, Chore, Feat

#48 [Style] : login, main, search 반응형 웹 수정
  pages/components/Navbar.tsx
  pages/login/index.tsx
  pages/main/index.tsx
  pages/search/index.tsx
Labels: Style

#49 [Style] : Main CSS 수정
  pages/main/index.tsx
Labels: Style

#50 [Style] : 스크롤탑 위치 수정
  pages/components/ScrollTopButton.tsx
  pages/main/GoToPostEditorButton.tsx
  pages/main/index.tsx
Labels: Style

#51 [Feat] : api 호출버튼 버그 수정
  pages/main/index.tsx
  pages/postEditor/index.tsx
  pages/posts/CommentsModal.tsx
  pages/posts/[postId].tsx
  pages/search/index.tsx
  pages/signup/index.tsx
Labels: Chore, Bug&Fix

#55 [Feat] : metadata 추가
  pages/_app.tsx
  pages/components/Navbar.tsx
  pages/postEditor/index.tsx
  pages/posts/CommentSection.tsx
  pages/posts/[postId].tsx
  pages/signup/index.tsx
Labels: Chore

#58 [Chore] : 일부 api 요청 ssr 처리, 프로필 이미지 렌더링 로직 변경
  pages/modify-userinfo/ChangePWModal.tsx
  pages/modify-userinfo/ChangeUserinfoModal.tsx
  pages/modify-userinfo/[userId].tsx
  pages/userinfo/FollowerModal.tsx
  pages/userinfo/FollowingModal.tsx
  pages/userinfo/[userId].tsx
  utils/atoms.tsx
  utils/type.ts
Labels: Chore, Bug&Fix
