Repository ZB-ChalKak/chalKak-front, pull requests merged in 2023-10, with the labels that each got.

#59 [Chore] : 게시글 상세페이지 CLS 문제 해결
  pages/posts/[postId].tsx
Labels: Chore

#60 [Bug&Fix] : 게시글 상세페이지 컴포넌트 겹침현상 해결
  pages/components/Navbar.tsx
  pages/posts/[postId].tsx
Labels: Bug&Fix

#61 [Feat] : recoil 새로고침 상태 유지
  package-lock.json
  package.json
  pages/components/Navbar.tsx
  pages/login/index.tsx
  pages/main/index.tsx
  utils/atoms.tsx
Labels: Feat

#62 [fix] : 타입 에러 수정
  pages/login/index.tsx
  pages/modify-userinfo/ChangeUserinfoModal.tsx
  pages/modify-userinfo/[userId].tsx
Labels: Bug&Fix
